---
version: '3'
services:
  gohealth:
    build: .
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 3009:3009
    restart: unless-stopped
    volumes:
      - logs:/app/logs

  db:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=LGS@dev230162#13
volumes:
  logs: